<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5b9172088fee9',
	'title' => 'Desenvolvedores(as)',
	'fields' => array(
		array(
			'key' => 'field_5b9173a76f6ad',
			'label' => 'URL do site',
			'name' => 'dev_url_site',
			'type' => 'url',
			'instructions' => 'Insira o endereço para o site oficial do desenvolvedor, estúdio ou equipe.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5b9172ec6f6a9',
			'label' => 'Descrição',
			'name' => 'dev_descricao',
			'type' => 'textarea',
			'instructions' => 'Insira uma descrição curta e breve sobre o desenvolvedor/estúdio/equipe e sobre seu trabalho. Limite de 500 caracteres.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 500,
			'rows' => 5,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5b9173126f6aa',
			'label' => 'Galeria de imagens',
			'name' => 'dev_galeria',
			'type' => 'repeater',
			'instructions' => 'Insira quantas imagens quiser sobre o trabalho do desenvolvedor/estúdio/equipe. Podem ser capturas de tela de jogos, artes conceituais, peças publicitárias ou outras imagens relacionadas. Somente imagens em JPG.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Adicionar imagem',
			'sub_fields' => array(
				array(
					'key' => 'field_5b9173496f6ab',
					'label' => 'Imagem',
					'name' => 'galeria_imagem',
					'type' => 'image',
					'instructions' => 'Imagem para a galeria',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'jpg',
				),
				array(
					'key' => 'field_5b9173866f6ac',
					'label' => 'Legenda',
					'name' => 'galeria_legenda',
					'type' => 'text',
					'instructions' => 'Legenda para a respectiva imagem. Limite de 100 caracteres.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 100,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'devs',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'page_attributes',
		8 => 'categories',
		9 => 'tags',
		10 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5b91b4220332f',
	'title' => 'Opções do site',
	'fields' => array(
		array(
			'key' => 'field_5b91b43a2abab',
			'label' => 'Banner de publicidade',
			'name' => 'banner_publicidade',
			'type' => 'textarea',
			'instructions' => 'Insira um código para exibição de banner de publicidade ou de banner institucional. Tamanho recomendado: 728x90 pixels',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => '',
		),
		array(
			'key' => 'field_5b91b4c12abac',
			'label' => 'Google Analytics',
			'name' => 'google_analytics',
			'type' => 'textarea',
			'instructions' => 'Insira aqui o código de integração do site com o Google Analytics',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'opcoes-site',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;